<?php
return array(
	'id' => 'ID',
	'cid' => '分类ID',
	'title' => '问题标题',
	'sub_title' => '副标题',
	'uid' => '用户ID',
	'username' => '发布人',
	'to_uid' => '针对的用户ID',
	'anonymous' => '是否匿名提交',
	'addtime' => '添加时间',
	'ip' => 'IP',
	'offercredit' => '是否提供悬赏',
	'credits' => '悬赏积分',
	'urgent' => '是否为紧急',
	'province_id' => '省份ID',
	'city_id' => '城市ID',
	'views' => '点击量',
	'keywords' => 'SEO关键字',
	'replies' => '回复数',
	'lastpost' => '最后回复时间',
	'lastpost_uid' => '最后回复用户ID',
	'lastposter' => '最后回复用户',
	'endtime' => '结束时间',
	'status' => '状态',
	'solvetime' => '解决时间',
	'verify' => '默认是否审核',
	'closed' => '是否关闭',
	'recommend' => '问题推荐',
	'display_order' => '显示顺序',
); 
