<?php
return array(
	'id' => 'ID',
	'parent' => '所属栏目',
	'name' => '栏目名称',
	'letter' => '索引字母',
	'model' => '模型',
	'url' => 'URL',
	'domain' => '绑定域名',
	'frame' => '封面图片',
	'type' => '类型',
	'item_count' => '下属栏目数',
	'htmlize' => '静态化',
	'html_list_url_rule' => '静态列表页URL规则',
	'html_view_url_rule' => '静态内容页URL规则',
	'path' => '静态页存放路径',
	'page_size' => '每页内容数量',
	'list_template' => '栏目列表页模板',
	'view_template' => '栏目内容页模板',
	'item_template' => '栏目列表显示样式',
	'display_order' => '排序',
	'seo_keywords' => 'SEO关键词',
	'seo_description' => 'SEO描述',
	'label_postfix' => '独立标签后缀',
	'config' => '配置',
);?>
