<?php
return array(
	'id' => '',
	'NO' => '',
	'interface_NO' => '',
	'name' => '',
	'subject' => '',
	'seller_uid' => '',
	'seller_username' => '',
	'buyer_uid' => '',
	'sid' => '',
	'buyer_username' => '',
	'phone' => '',
	'email' => '',
	'address' => '',
	'interface' => '',
	'amount' => '',
	'number' => '',
	'ip' => '',
	'timestamp' => '',
	'status' => '',
	'paid' => '',
	'notify' => '',
	'content' => '',
);?>
