<?php
return array(
	'id' => 'ID',
	'model' => '模型',
	'title' => '标题',
	'title_color' => '颜色',
	'title_bold' => '加粗',
	'sub_title' => '副标题',
	'cid' => '内容栏目',
	'frame' => '封面图片',
	'url' => '跳转地址',
	'uid' => '用户ID',
	'author' => '作者',
	'editer' => '编辑',
	'username' => '用户名',
	'attributes' => '内容属性',
	'summary' => '内容摘要',
	'pages' => '页数',
	'html_view_url_rule' => '内容页静态化规则',
	'views' => '点击量',
	'comments' => '评论',
	'timestamp' => '发布时间',
	'create_time' => '创建时间',
	'update_time' => '更新时间',
	'list_order' => '排序',
	'verified' => '审核',
	'ever_verified' => '',
	'allow_comment' => '允许评论',
	'allow_mood' => '允许顶',
	'credit' => '收费',
	'credit_type' => '内容收费',
	'digg' => '顶',
	'trample' => '',
);?>
