<?php
return array(
	'id' => '',
	'model' => '',
	'parent' => '',
	'name' => '',
	'alias' => '',
	'type' => '',
	'part' => '',
	'list_table' => '',
	'filterable' => '',
	'orderby' => '',
	'not_null' => '',
	'length' => '',
	'is_unsigned' => '',
	'editable' => '',
	'default_value' => '',
	'data' => '',
	'config' => '',
	'widget' => '',
	'widget_addon_attr' => '',
	'display_order' => '',
	'units' => '',
	'jsreg' => '',
	'jsregmsg' => '',
	'color' => '',
	'description' => '',
);?>
