<?php
return array(
	'id' => '',
	'cid' => '',
	'uid' => '',
	'username' => '',
	'email' => '',
	'ip' => '',
	'ico' => '',
	'oicq' => '',
	'weburl' => '',
	'blogurl' => '',
	'telephone' => '',
	'title' => '',
	'content' => '',
	'verified' => '',
	'ifhide' => '',
	'posttime' => '',
	'list' => '',
	'digg' => '',
	'trample' => '',
	'reply' => '',
	'replytime' => '',
	'replyer' => '',
);?>
