<?php
return array(
	'id' => '',
	'department' => '',
	'type' => '',
	'visual' => '',
	'number' => '',
	'uid' => '',
	'username' => '',
	'code' => '',
	'gender' => '',
	'age' => '',
	'phone' => '',
	'ip' => '',
	'email' => '',
	'id_type' => '',
	'id_num' => '',
	'profession' => '',
	'education' => '',
	'address' => '',
	'title' => '',
	'create_time' => '',
	'update_time' => '',
	'status' => '',
	'status_change_time' => '',
	'askable' => '',
	'log' => '',
	'solve_time' => '',
	'solve_uid' => '',
	'solve_department' => '',
	'solve_name' => '',
	'comment' => '',
	'comment_time' => '',
);?>
