<?php
return array(
	'id' => '',
	'username' => '',
	'password' => '',
	'salt' => '',
	'number' => '',
	'email' => '',
	'name' => '',
	'phone' => '',
	'cell_phone' => '',
	'address' => '',
	'fax' => '',
	'qq' => '',
	'msn' => '',
	'gender' => '',
	'birthday' => '',
	'icon' => '',
	'role_id' => '',
	'role_gid' => '',
	'last_role_id' => '',
	'is_admin' => '',
	'is_founder' => '',
	'friend_setting' => '',
	'friends' => '',
	'new_messages' => '',
	'status' => '',
	'register_time' => '',
	'register_ip' => '',
	'last_login_ip' => '',
	'pinyin' => '',
	'last_login' => '',
	'login_time' => '',
	'display_order' => '',
	'memo' => '',
	'homepage' => '',
);?>
