<?php
return array(
	'uid' => '',
	'name' => '',
	'email' => '',
	'gender' => '',
	'married' => '',
	'birthday' => '',
	'national' => '',
	'idcard' => '',
	'worktime' => '',
	'census' => '',
	'education' => '',
	'profession' => '',
	'address' => '',
	'telephone' => '',
	'mobile' => '',
	'photo' => '',
	'postalcode' => '',
	'website' => '',
	'height' => '',
	'weight' => '',
	'company' => '',
	'job' => '',
	'forte' => '',
	'introduction' => '',
	'status' => '',
);?>
