<?php
return array(
	'id' => '',
	'tuid' => '',
	'title' => '',
	'course' => '',
	'course_cat' => '',
	'duration' => '',
	'industry' => '',
	'number' => '',
	'gender' => '',
	'city' => '',
	'education' => '',
	'married' => '',
	'profession' => '',
	'age' => '',
	'begintime' => '',
	'endtime' => '',
	'timestamp' => '',
	'status' => '',
	'view' => '',
	'send' => '',
	'effect' => '',
	'content' => '',
);?>
