<?php
return array(
	'uid' => '',
	'name' => '',
	'industry' => '',
	'properties' => '',
	'city' => '',
	'address' => '',
	'size' => '',
	'foundtime' => '',
	'money' => '',
	'postalcode' => '',
	'contact' => '',
	'telephone' => '',
	'email' => '',
	'website' => '',
	'logo' => '',
	'introduction' => '',
	'status' => '',
);?>
