<?php
return array(
	'uid' => '',
	'name' => '',
	'email' => '',
	'gender' => '',
	'married' => '',
	'birthday' => '',
	'national' => '',
	'idcard' => '',
	'experience' => '',
	'census' => '',
	'education' => '',
	'profession' => '',
	'address' => '',
	'telephone' => '',
	'mobile' => '',
	'situation' => '',
	'photo' => '',
	'postalcode' => '',
	'website' => '',
	'height' => '',
	'weight' => '',
	'resume1' => '',
	'resume2' => '',
	'default_resume' => '',
	'status' => '',
);?>
