<?php
return array(
	'id' => '',
	'title' => '',
	'cuid' => '',
	'industry' => '',
	'job' => '',
	'city' => '',
	'count' => '',
	'salary' => '',
	'kind' => '',
	'experience' => '',
	'entrytime' => '',
	'gender' => '',
	'profession' => '',
	'age' => '',
	'education' => '',
	'married' => '',
	'begintime' => '',
	'endtime' => '',
	'timestamp' => '',
	'lastupdate' => '',
	'view' => '',
	'send' => '',
	'list_order' => '',
	'status' => '',
	'content' => '',
);?>
