<?php
return array(
	'id' => '',
	'parent' => '',
	'name' => '',
	'letter' => '',
	'model' => '',
	'url' => '',
	'domain' => '',
	'frame' => '',
	'type' => '',
	'item_count' => '',
	'iswork' => '',
	'htmlize' => '',
	'html_list_url_rule' => '',
	'html_view_url_rule' => '',
	'path' => '',
	'page_size' => '',
	'list_template' => '',
	'view_template' => '',
	'item_template' => '',
	'display_order' => '',
	'seo_keywords' => '',
	'seo_description' => '',
	'label_postfix' => '',
	'config' => '',
);?>
