<?php
return array(
	'id' => 'ID',
	'number' => '数量',
	'model' => '模型',
	'title' => '标题',
	'title_color' => '标题颜色',
	'title_bold' => '标题加粗',
	'sub_title' => '副标题',
	'cid' => '内容栏目',
	'frame' => '封面图片',
	'url' => '封面图片',
	'uid' => '用户ID',
	'username' => '用户名',
	'attributes' => '内容属性',
	'summary' => '内容摘要',
	'pages' => '内容页数',
	'html_view_url_rule' => '内容页静态化规则',
	'views' => '点击量',
	'comments' => '评论数',
	'timestamp' => '发布时间',
	'verifytime' => '审核时间',
	'update_time' => '更新时间',
	'list_order' => '列表排序',
	'verified' => '审核',
	'ever_verified' => '通过审核',
	'allow_comment' => '允许评论',
	'allow_mood' => '允许心情顶',
	'credit' => '费用',
	'credit_type' => '费用类型',
);?>
