<?php
return array(
	'id' => '',
	'number' => '',
	'model' => '',
	'cid' => '',
	'uid' => '',
	'username' => '',
	'title' => '',
	'title_color' => '',
	'title_bold' => '',
	'sub_title' => '',
	'frame' => '',
	'url' => '',
	'attributes' => '',
	'summary' => '',
	'source' => '',
	'keywords' => '',
	'verified' => '',
	'timestamp' => '',
	'verifytime' => '',
	'list_order' => '',
	'update_time' => '',
	'pages' => '',
	'html_view_url_rule' => '',
	'template' => '',
	'views' => '',
	'comments' => '',
	'seo_keywords' => '',
	'seo_description' => '',
	'label_postfix' => '',
);?>
