<?php
return array(
	'id' => '',
	'number' => '',
	'model' => '',
	'title' => '',
	'title_color' => '',
	'title_bold' => '',
	'sub_title' => '',
	'cid' => '',
	'frame' => '',
	'url' => '',
	'uid' => '',
	'username' => '',
	'attributes' => '',
	'summary' => '',
	'pages' => '',
	'html_view_url_rule' => '',
	'views' => '',
	'comments' => '',
	'timestamp' => '',
	'verifytime' => '',
	'update_time' => '',
	'list_order' => '',
	'verified' => '',
	'ever_verified' => '',
	'allow_comment' => '',
	'allow_mood' => '',
	'credit' => '',
	'credit_type' => '',
);?>
