<?php
return array(
	'id' => 'ID',
	'model' => '模型',
	'parent' => '',
	'name' => '字段名称',
	'alias' => '字段别名',
	'type' => '类型',
	'list_table' => '列表字段',
	'filterable' => '搜索的过滤字段',
	'orderby' => '排序',
	'not_null' => '字段必须填写',
	'length' => '字段长度',
	'is_unsigned' => '是否正数',
	'editable' => '是否可编辑',
	'default_value' => '字段默认值',
	'data' => '日期',
	'config' => '配置',
	'widget' => '字段输入方式',
	'widget_addon_attr' => '输入容器附加属性',
	'display_order' => '显示顺序',
	'units' => '单位',
	'description' => '描述',
);?>
