<?php
return array(
	'id' => 'ID',
	'number' => '编号',
	'model' => '模型',
	'cid' => '内容栏目',
	'uid' => '用户ID',
	'username' => '用户名',
	'title' => '标题',
	'title_color' => '标题颜色',
	'title_bold' => '标题加粗',
	'sub_title' => '副标题',
	'frame' => '封面图片',
	'url' => '跳转地址',
	'attributes' => '内容属性',
	'summary' => '内容摘要',
	'source' => '内容出处',
	'author' => '作者',
	'editer' => '编辑',
	'keywords' => '关键字',
	'verified' => '审核',
	'timestamp' => '发布时间',
	'verifytime' => '审核时间',
	'list_order' => '列表排序',
	'update_time' => '更新时间',
	'pages' => '内容页数',
	'html_view_url_rule' => '内容页静态化规则',
	'template' => '模板',
	'views' => '点击量',
	'comments' => '评论数',
	'seo_keywords' => 'SEO关键词',
	'seo_description' => 'SEO描述',
	'label_postfix' => '独立标签后缀',
);?>
