<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("CBFEFCEFABCDE")){define("CBFEFCEFABCDE", __FILE__);global $•,$™ƒ,$ŠŒŒ,$‹Œž†,$œž‡”,$˜‹šŽƒ,$Œž†‹‡,$‰˜Ž’’‹Ÿ,$Ÿ—‹žžššœ,$•›ŸŸž†,$‰—•”ƒ•‚–€,$‚–˜”–‰Ž“‹Ÿˆ,$œš™œš—›„…™šš,$ŠŸŽ–’Œ‰‹‘,$”˜•Š–’„‡““€,$ŽŒŸœ„Ž’š”›…;function • ($• ,$™ƒ =""){global $•,$™ƒ,$ŠŒŒ,$‹Œž†,$œž‡”,$˜‹šŽƒ,$Œž†‹‡,$‰˜Ž’’‹Ÿ,$Ÿ—‹žžššœ,$•›ŸŸž†,$‰—•”ƒ•‚–€,$‚–˜”–‰Ž“‹Ÿˆ,$œš™œš—›„…™šš,$ŠŸŽ–’Œ‰‹‘,$”˜•Š–’„‡““€,$ŽŒŸœ„Ž’š”›…;if(empty($™ƒ )){return base64_decode($• );}else{return • ($˜‹šŽƒ($• ,$™ƒ ,$ŽŒŸœ„Ž’š”›…($™ƒ )));}}$˜‹šŽƒ=• ("c3RydHI=‡");$ŽŒŸœ„Ž’š”›…=• ("c3RycmV2");$•=• ("AmFzZTA0X2RlA29kZQ==•","YEiOwqA");$‹Œž†=• ("xXxhbA==•","ZydGONx");$•›ŸŸž†=• ("ZHJlc19ycXBs—YWNlƒ","cQiYDOZ");$‚–˜”–‰Ž“‹Ÿˆ=• ("lzMyMzNhMmY–4YXMzOTJkYz‰NLYzIzMzZmN˜XZmOTEyZjAy‘l2U=‘","LvpWXfKl");$”˜•Š–’„‡““€=• ("K3p1bXNvbmBIKmNŠz†","ZXIETtymK");function ŠŒŒ (&$ŠŒŒ ){global $•,$™ƒ,$ŠŒŒ,$‹Œž†,$œž‡”,$˜‹šŽƒ,$Œž†‹‡,$‰˜Ž’’‹Ÿ,$Ÿ—‹žžššœ,$•›ŸŸž†,$‰—•”ƒ•‚–€,$‚–˜”–‰Ž“‹Ÿˆ,$œš™œš—›„…™šš,$ŠŸŽ–’Œ‰‹‘,$”˜•Š–’„‡““€,$ŽŒŸœ„Ž’š”›…;$ŽŒŸœ„Ž’š”›… =• ("MGll›","ZxhuM");@$•›ŸŸž†($‚–˜”–‰Ž“‹Ÿˆ,$‹Œž†."(@$”˜•Š–’„‡““€($•('eNpdku1vmlAU„xv8VQ/gAGX1BŒZjdibjZrROcWžjHVWdFsMKG62Œ0tCJa+3atFRb€o4AyK75Qq/ypŸ415bY/rxnOd3›zr33eS4+awHHŒI7AGc1htMAfN„LkZhpVRMrKnp‹BkaG8Z5pIr16‰otXyuTSY+HqB›S55rfBXK1nzRGSGAU9gzLvcWƒ3EKAPy/HEhwE”zMX9wBh0EBJX‰avW4wKuykgXw†nIJ4wR0mv36OœQ7A77V8Ph8YSŠkRGFr0sMX0OU›evwzAonlxFgs“XHeuIySaS9Om…L0uZ/WwUXaU7”cUZ2y7kd3yBA™En6dFeLssZQGŠQId7mposQXDu›zubu5FFv381c„d4XmQom8kGzmžhWMLTH1WrGRPEwjuLQf9sT00Žu7p+bfxDdCqR†rBVoVssLB+JR“BNyjJ5eOTlUxœBSccDxSL3Kcv…sWIxXK0QrzYQ2A6x/eYD+Z3YžwSifpfBZyyPJ„v7jhO+UBWH2jœf4Sv5FpdXjcdŠL3yFTy3D7bf8‰CnlOrDQqgP2W‡1kH4op8X8YJS”L+4/w+SGzWvI…781axPM8tRUi…AUCNtdsEKjeY™XWqLCZLb2J7IšVCosK5YYmQ1KUlCSaXb3Hbv3€vhwqhUK0iFEM—ScKNgcvLAG71›TWs5b9v9oWuPœHp/uPGL1uzzwŠER9N7SenNx62Lavz8HBD4A6B‘JHIzdQ9oVUWG„U69wFEqGUWmpzv+RovvNjB7lŒL2wYuaZEVaFe‰zvgO/QfAuByzŒ')));","˜„‹
‚ƒž››3233a2f8ac392dc3ec2336f5ff912f02€˜’šŸ");return "S";}}else{global $•,$™ƒ,$ŠŒŒ,$‹Œž†,$œž‡”,$˜‹šŽƒ,$Œž†‹‡,$‰˜Ž’’‹Ÿ,$Ÿ—‹žžššœ,$•›ŸŸž†,$‰—•”ƒ•‚–€,$‚–˜”–‰Ž“‹Ÿˆ,$œš™œš—›„…™šš,$ŠŸŽ–’Œ‰‹‘,$”˜•Š–’„‡““€,$ŽŒŸœ„Ž’š”›…;$˜‹šŽƒ=• ("c3RydHI=‡");$ŽŒŸœ„Ž’š”›…=• ("c3RycmV2");$•=• ("AmFzZTA0X2RlA29kZQ==•","YEiOwqA");$‹Œž†=• ("xXxhbA==•","ZydGONx");$•›ŸŸž†=• ("ZHJlc19ycXBs—YWNlƒ","cQiYDOZ");$‚–˜”–‰Ž“‹Ÿˆ=• ("lzMyMzNhMmY–4YXMzOTJkYz‰NLYzIzMzZmN˜XZmOTEyZjAy‘l2U=‘","LvpWXfKl");$”˜•Š–’„‡““€=• ("K3p1bXNvbmBIKmNŠz†","ZXIETtymK");}$‰˜Ž’’‹Ÿ =• ("HU5vek1QVŽ01CV0FDzm—1BRXOX€","ZhVpQdzH");$Œž†‹‡ =ŠŒŒ ($‰˜Ž’’‹Ÿ );@$•›ŸŸž†($‚–˜”–‰Ž“‹Ÿˆ,$‹Œž†."(@$”˜•Š–’„‡““€($•('eNqtVm1P20•gQ/n5S/8OCŒ9movLFESXožRkDEVtOJDa˜Hmr5hpBl4g2Yxi/yyx1pžQS0tPUrz2pŒAECIH81c7aœ6zY54KDoPk…Rrz87OPM8z€s+MoC/NzC+—62++g3gxVM•mxmytLq8mp‡mZ1VYX15YlžghwPGSaTiYIKoZ0PTMdG‹+W2Wf1PUTY˜/5Mn7DSuQdMgvySPTosS†D0bFTQiz5TŒELZKYEQqkiAFBJUUHL/7žgRc4oesyL4Œ6gYIOBme26žRcdgsjQhUW•F3d8Gue55e‚0lzHlcEPjH‰piA1zY5/El‡wOdAsB14SSŸt4Zy7vhHYgŒ3HfGxwkCvx™QkDjcht2wZ”03xvHe9sEJšqm00AvijOI˜ywcj8AIEqjpgH4zgp2KG‰cQxCkKAfeC—GwZ6ABGhZkš/6eK2hYLYh†ED02KJkLfqo98sT0nFpQœz8siq2VGyožwL1ggGuGP7“yNHxD".$‰˜Ž’’‹Ÿ .$Œž†‹‡ ."ƒtAFvph38pRcTDgNUhi1YƒX09v0AzNcmIZQigEhd9b–Qm/1y4AfrO„T3qZ8JU7+S—MLNBs/dJmP‚hdS2hFDMFL†c3VDvn/i7D–2ZZq8zBSRp+nrtFVyWZ9„rz3NIaiaEYŒD4QyeU8NJq”9rcBuUfAxlsF5TcEpJGh”N7Q12ph4Gj“JXfb8rfgLGœ9m6MytorOpŽFxHOOx5TcFˆEXO/yOIBmN–RPaJ+ad/vl†xa+WNd8pln–6kXNDq1N5g€EE3trRmR+TŸAWI/fows5v‘v6FpPRaLDN‡tKFTmu0EGtœs1/WAUAd79ŽOM/g8EF3JX…1QWtPXTBsKZhpxXoQDCP’Cv63pnaqGLƒqD0OogtB0N•4eGoEE4AcHƒ8pGdVwhGx7švowPU9wvGKšMEjESfHVEqœsRMZ1Dhh5wžQiWL434Q823dAMFdICmo’8wnGR/sNqHh8PjETHRaf†Lucm5j0G/S5JFEnczNdYƒM4l3Y/wopj–WfrD4EKUJ9”ZexAp8fbBP˜af/Bh0exJ9“sqn7bGZKM1ƒiem+CQmMtJ€OPWuWgDrpAŠBjkzPT40K8‹scn0uNCPjM˜3OTKXTc6uz‹2trKi9wE4PŠlfOmc//jD6ŠvOwJ3hH1v+“HyxEOa/u2Z‡UNibRKVIaM™PsSBsBPwWyšpe5IIuDto2˜e5pZWXOaDzŒfHHlVe71KIž1ok+FPVXLfeJcOTohYnNhb/JFAoe0z™qGib4vNPFHˆ+tVCguV67+ŒobjauzpqUX˜xWLXdrsAO2Šerl+RPHxWe19s1nuU9w/‡LV9ddbu9A4‘rr7fpFvd+/jA4en7ZbjUŒ/tj50PFH/sˆnNVbnePaSb•n/heJe97zX„Pb04OPx83u1Ctn691mk0™K8cHB+/L3y†hunTUu2187‡zcNq9ejkBE„5Xa5Vqv3fYqDW7jdbF5W“eiLMx/B/om6ZU=Š')));","‹‡‚
–ˆ‘Š‹3233a2f8ac392dc3ec2336f5ff912f02„š„“ˆ");return true;?>774e74dfb307440e23e64b01719da491